#ifndef PCH_H
#define PCH_H

#pragma once
#include <iostream>
#include <cpprest/http_client.h>
#include <cpprest/filestream.h>
#include <cpprest/http_headers.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <set>
#include <unordered_map>
#include <fstream>
#include <rapidjson/document.h>
#include <optional>
#include <cpptoml.h>
#include <regex>
#include <filesystem>
#include <cstdio>
#include <algorithm>
#endif //PCH_H
